import http from 'node:http';
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {join, extname} from 'node:path';
import {randomBytes, timingSafeEqual, scryptSync} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const APP_VERSION=process.env.APP_VERSION||'0.6.1',PORT=Number(process.env.PORT||4380), ROOT=fileURLToPath(new URL('.',import.meta.url)), PUBLIC=join(ROOT,'public'), DATA=process.env.DATA_DIR||join(ROOT,'data'), DB=join(DATA,'hub.json');
const sessions=new Map(),pdfJobs=new Map(),maxBody=30_000_000;
const seed={transactions:[],marketing:[{id:'welcome',title:'Build the fall campaign calendar',owner:'Communications',status:'In progress',due:'',channel:'All channels'}],newsletters:[{id:'first-issue',title:'Next RFD newsletter',status:'Outline',writer:'',due:'',sections:[{id:'opening',title:'Opening note',notes:'Why this moment matters',status:'Drafting'},{id:'action',title:'Action items',notes:'Events, volunteer asks, and links',status:'Needs input'}]}],integrations:{vikunja:{url:'',token:'',project:'Night of the Living Loud'},eventbrite:{eventId:'',token:''},buffer:{token:'',facebookChannel:'',instagramChannel:''}},eventMetrics:{sponsorsCommitted:0,revenueCommitted:0},activity:[]};
let db=await load();
db.integrations.keycloak={url:'',realm:'',clientId:'rfd-board-hub',clientSecret:'',enabled:false,...(db.integrations.keycloak||{})};
db.events=Array.isArray(db.events)&&db.events.length?db.events:[{id:'night-of-the-living-loud',title:'Night of the Living Loud',vikunjaProject:db.integrations.vikunja.project||'Night of the Living Loud',eventbriteEventId:db.integrations.eventbrite.eventId||''}];
db.marketingAssets=Array.isArray(db.marketingAssets)?db.marketingAssets:[];
db.generatedPdfs=Array.isArray(db.generatedPdfs)?db.generatedPdfs:[];for(const item of db.generatedPdfs)pdfJobs.set(item.id,item);
async function load(){await mkdir(DATA,{recursive:true});if(!existsSync(DB)){await writeFile(DB,JSON.stringify(seed,null,2));return structuredClone(seed)}try{return {...structuredClone(seed),...JSON.parse(await readFile(DB,'utf8'))}}catch{return structuredClone(seed)}}
async function save(){await writeFile(DB,JSON.stringify(db,null,2))}
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=').map(decodeURIComponent)));
const session=req=>{const sid=cookies(req).rfd_session,value=sessions.get(sid);if(value?.expiresAt&&value.expiresAt<Date.now()){sessions.delete(sid);return null}return value};
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>maxBody)throw Error('Request too large')}return raw?JSON.parse(raw):{}}
function hash(value,salt){return scryptSync(value,salt,32)}
function configured(){return Boolean(process.env.BOARD_PASSWORD_HASH&&process.env.BOARD_PASSWORD_SALT)||Boolean(process.env.BOARD_PASSWORD)}
function passwordOk(value){if(process.env.BOARD_PASSWORD_HASH&&process.env.BOARD_PASSWORD_SALT){const got=hash(value,process.env.BOARD_PASSWORD_SALT),expected=Buffer.from(process.env.BOARD_PASSWORD_HASH,'hex');return got.length===expected.length&&timingSafeEqual(got,expected)}return Boolean(process.env.BOARD_PASSWORD)&&value===process.env.BOARD_PASSWORD}
function secureRequest(req){const forwarded=String(req.headers['x-forwarded-proto']||'').split(',')[0].trim().toLowerCase();return process.env.COOKIE_SECURE==='true'||forwarded==='https'||Boolean(req.socket?.encrypted)}
async function keycloakLogin(username,password){const c=db.integrations.keycloak;if(!c.enabled||!c.url||!c.realm||!c.clientId)throw Error('Keycloak login is not configured');const form=new URLSearchParams({grant_type:'password',client_id:c.clientId,username,password,scope:'openid profile email'});if(c.clientSecret)form.set('client_secret',c.clientSecret);const endpoint=`${c.url.replace(/\/$/,'')}/realms/${encodeURIComponent(c.realm)}/protocol/openid-connect/token`,response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(15000)}),data=await response.json().catch(()=>({}));if(!response.ok)throw Error(response.status===401||response.status===400?'Username or password was not accepted.':data.error_description||`Keycloak returned ${response.status}`);let claims={};try{claims=JSON.parse(Buffer.from(data.access_token.split('.')[1],'base64url').toString())}catch{}return {name:claims.name||claims.preferred_username||username,username:claims.preferred_username||username,sub:claims.sub||'',keycloakTokenExpiresAt:Date.now()+Math.max(60,Number(data.expires_in||300))*1000,expiresAt:Date.now()+12*60*60*1000}}
function requireAuth(req,res){if(process.env.AUTH_BYPASS==='true')return {name:'Local preview'};const s=session(req);if(!s){json(res,401,{error:'Sign in required'});return null}return s}
const clean=v=>String(v??'').trim().slice(0,5000), id=()=>randomBytes(8).toString('hex');
function audit(user,action,label){db.activity.unshift({id:id(),at:new Date().toISOString(),user:user.name,action,label:clean(label).slice(0,100)});db.activity=db.activity.slice(0,100)}
const apiBase=url=>`${String(url||'').replace(/\/$/,'').replace(/\/api\/v1$/,'')}/api/v1`;
async function fetchJson(url,options={},label='Service'){const r=await fetch(url,{...options,signal:AbortSignal.timeout(15000)}),text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(`${label} returned invalid data`)}if(!r.ok)throw Error(data.message||data.error_description||data.error||`${label} returned ${r.status}`);return data}
async function eventbriteSnapshot(){const c=db.integrations.eventbrite;if(!c.eventId||!c.token)throw Error('Configure Eventbrite in Settings');const headers={Authorization:`Bearer ${c.token}`,Accept:'application/json'},base='https://www.eventbriteapi.com/v3',event=await fetchJson(`${base}/events/${encodeURIComponent(c.eventId)}/`,{headers},'Eventbrite'),attendees=[],orders=[];for(let page=1;page<=50;page++){const d=await fetchJson(`${base}/events/${c.eventId}/attendees/?page=${page}`,{headers},'Eventbrite attendees');attendees.push(...(d.attendees||[]));if(!d.pagination?.has_more_items)break}for(let page=1;page<=50;page++){const d=await fetchJson(`${base}/events/${c.eventId}/orders/?page=${page}`,{headers},'Eventbrite orders');orders.push(...(d.orders||[]));if(!d.pagination?.has_more_items)break}const active=attendees.filter(x=>!x.cancelled&&!x.refunded),byTicket={};for(const x of active){const name=x.ticket_class_name||'Other';byTicket[name]=(byTicket[name]||0)+Math.max(1,Number(x.quantity)||1)}return {event:event.name?.text||'Night of the Living Loud',ticketsSold:active.length,checkedIn:active.filter(x=>x.checked_in).length,orders:orders.filter(x=>!x.status||x.status==='placed').length,grossRevenue:active.reduce((s,x)=>s+Number(x.costs?.gross?.value||0),0)/100,capacity:Number(event.capacity||0),byTicket}}
async function livingLoud(){const c=db.integrations.vikunja;if(!c.url||!c.token)throw Error('Configure Vikunja in Settings');const headers={Authorization:`Bearer ${c.token}`,Accept:'application/json'},base=apiBase(c.url),projects=await fetchJson(`${base}/projects?per_page=100`,{headers},'Vikunja'),project=(Array.isArray(projects)?projects:[]).find(x=>String(x.title).toLowerCase()===String(c.project).toLowerCase());if(!project)throw Error(`Vikunja project “${c.project}” was not found`);const tasks=[];for(let page=1;page<=20;page++){const batch=await fetchJson(`${base}/projects/${project.id}/tasks?page=${page}&per_page=50`,{headers},'Vikunja tasks');if(!Array.isArray(batch)||!batch.length)break;tasks.push(...batch);if(batch.length<50)break}const now=Date.now(),week=now+7*864e5,item=x=>{const due=x.due_date||'',t=new Date(due).getTime();return {id:x.id,title:x.title,done:Boolean(x.done),dueDate:due,overdue:Boolean(!x.done&&t&&t<now),priority:Number(x.priority||0),assignees:(x.assignees||[]).map(p=>p.username||p.name||`User ${p.id}`)}};const items=tasks.map(item),open=items.filter(x=>!x.done),people={};for(const task of open)for(const person of task.assignees)people[person]=(people[person]||0)+1;let ticketing=null;try{ticketing=await eventbriteSnapshot()}catch(e){ticketing={error:e.message}}return {project:{title:project.title,url:`${String(c.url).replace(/\/$/,'')}/projects/${project.id}`},metrics:db.eventMetrics,ticketing,summary:{total:items.length,done:items.length-open.length,open:open.length,overdue:open.filter(x=>x.overdue).length,completion:items.length?Math.round((items.length-open.length)/items.length*100):0},people,upcoming:open.filter(x=>{const t=new Date(x.dueDate).getTime();return t>=now&&t<=week}).slice(0,12),urgent:open.filter(x=>x.priority>=4||x.overdue).slice(0,12)} }
async function bufferCall(query,variables={}){const token=db.integrations.buffer.token;if(!token)throw Error('Configure Buffer in Settings');return (await fetchJson('https://api.buffer.com',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query,variables})},'Buffer')).data||{}}
const metricKey=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function summarize(posts,start,end){const selected=[],totals={};for(const post of posts){const published=new Date(post.dueAt);if(!(published>=start&&published<end))continue;const values={};for(const m of post.metrics||[]){const k=metricKey(m.type||m.name),v=Number(m.value||0);values[k]=v;totals[k]=(totals[k]||0)+v}const engagements=(values.reactions??values.likes??0)+['comments','shares','saves','clicks','linkclicks'].reduce((s,k)=>s+(values[k]||0),0),reach=values.reach||values.impressions||0;selected.push({...post,metricValues:values,derivedEngagements:engagements,derivedEngagementRate:reach?engagements/reach*100:null})}selected.sort((a,b)=>(b.derivedEngagementRate??-1)-(a.derivedEngagementRate??-1));const engagements=selected.reduce((s,x)=>s+x.derivedEngagements,0),reach=totals.reach||totals.impressions||0,count=selected.length;return {postCount:count,totals,derived:{engagements,engagementRate:reach?engagements/reach*100:null,averageEngagements:count?engagements/count:0,postsPerWeek:count/Math.max((end-start)/6048e5,1/7)},posts:selected}}
async function bufferInsights(){const account=await bufferCall('query { account { organizations { id name } } }'),orgs=account.account?.organizations||[];if(!orgs.length)throw Error('Buffer returned no organizations');const chosen=[db.integrations.buffer.facebookChannel,db.integrations.buffer.instagramChannel].filter(Boolean),end=new Date(),start=new Date(end-30*864e5),previous=new Date(start-30*864e5),posts=[];for(const org of orgs){let ids=chosen;if(!ids.length){const result=await bufferCall('query Channels($organization:OrganizationId!){channels(input:{organizationId:$organization}){id service}}',{organization:org.id});ids=(result.channels||[]).filter(x=>['facebook','instagram'].includes(String(x.service).toLowerCase())).map(x=>x.id)}if(!ids.length)continue;const query='query Insights($organization:OrganizationId!,$channels:[ChannelId!]!,$start:DateTime!,$after:String){posts(first:100,after:$after,input:{organizationId:$organization,sort:[{field:dueAt,direction:desc}],filter:{status:[sent],channelIds:$channels,startDate:$start}}){edges{node{id text dueAt channelId externalLink metrics{type name value unit} metricsUpdatedAt}}}}';const result=await bufferCall(query,{organization:org.id,channels:ids,start:previous.toISOString(),after:null});posts.push(...(result.posts?.edges||[]).map(x=>x.node))}return {days:30,current:summarize(posts,start,end),previous:summarize(posts,previous,start),channels:chosen.length||'auto'} }
async function bufferAggregate(organization,channels,start,end){const query='query Aggregate($organization:OrganizationId!,$channels:[ChannelId!]!,$start:DateTime!,$end:DateTime!){aggregatedPostMetrics(input:{organizationId:$organization,channelIds:$channels,startDateTime:$start,endDateTime:$end}){metrics{type name value unit}metricsUpdatedAt}}';return (await bufferCall(query,{organization,channels,start:start.toISOString(),end:end.toISOString()})).aggregatedPostMetrics||{}}
function summarizeAggregate(groups,start,end){const totals={},meta={},percentages={};let count=0;for(const group of groups){const metrics=group.metrics||[],groupCount=Number(metrics.find(m=>metricKey(m.type)==='postcount')?.value||0);count+=groupCount;for(const m of metrics){const key=metricKey(m.type||m.name),value=Number(m.value||0),unit=m.unit||'count';meta[key]={name:m.name||m.type||key,unit};if(unit==='percentage')(percentages[key]||=[]).push([value,groupCount]);else totals[key]=(totals[key]||0)+value}}for(const [key,values] of Object.entries(percentages)){const weight=values.reduce((s,x)=>s+x[1],0);totals[key]=weight?values.reduce((s,x)=>s+x[0]*x[1],0)/weight:0}const engagements=(totals.reactions??totals.likes??0)+['comments','shares','saves','clicks','linkclicks'].reduce((s,k)=>s+(totals[k]||0),0),reach=totals.reach||totals.impressions||0;return {postCount:Math.round(count),totals,metricMeta:meta,derived:{engagements,engagementRate:reach?engagements/reach*100:null,averageEngagements:count?engagements/count:0,postsPerWeek:count/Math.max((end-start)/6048e5,1/7)},posts:[]}}
async function bufferInsightsDirect(){const account=await bufferCall('query { account { organizations { id name } } }'),orgs=account.account?.organizations||[];if(!orgs.length)throw Error('Buffer returned no organizations for this API key');const end=new Date(),start=new Date(end-30*864e5),previousStart=new Date(start-30*864e5),currentGroups=[],previousGroups=[],posts=[],warnings=[];let channelCount=0;for(const org of orgs){try{const result=await bufferCall('query Channels($organization:OrganizationId!){channels(input:{organizationId:$organization}){id name displayName service}}',{organization:org.id}),configured=[db.integrations.buffer.facebookChannel,db.integrations.buffer.instagramChannel].filter(Boolean),channels=(result.channels||[]).filter(x=>['facebook','instagram'].includes(String(x.service).toLowerCase())&&(!configured.length||configured.includes(x.id))),ids=channels.map(x=>x.id);channelCount+=ids.length;if(!ids.length)continue;currentGroups.push(await bufferAggregate(org.id,ids,start,end));previousGroups.push(await bufferAggregate(org.id,ids,previousStart,start));try{const query='query Insights($organization:OrganizationId!,$channels:[ChannelId!]!,$start:DateTime!,$after:String){posts(first:100,after:$after,input:{organizationId:$organization,sort:[{field:dueAt,direction:desc}],filter:{status:[sent],channelIds:$channels,startDate:$start}}){edges{node{id text dueAt channelId externalLink metrics{type name value unit} metricsUpdatedAt}}}}';const data=await bufferCall(query,{organization:org.id,channels:ids,start:start.toISOString(),after:null});posts.push(...(data.posts?.edges||[]).map(x=>x.node))}catch(e){warnings.push(`Top posts: ${e.message}`)}}catch(e){warnings.push(`${org.name||org.id}: ${e.message}`)}}if(!channelCount)throw Error(warnings[0]||'No Facebook or Instagram channels were found');const current=summarizeAggregate(currentGroups,start,end),previous=summarizeAggregate(previousGroups,previousStart,start);current.posts=summarize(posts,start,end).posts.slice(0,50);return {days:30,current,previous,channels:channelCount,warnings,experimental:true}}
async function bufferInsightsRich(days=30,platformFilter='all'){const account=await bufferCall('query { account { organizations { id name } } }'),orgs=account.account?.organizations||[];if(!orgs.length)throw Error('Buffer returned no organizations for this API key');const end=new Date(),start=new Date(end-days*864e5),previousStart=new Date(start-days*864e5),groups={Facebook:[],Instagram:[]},priorGroups={Facebook:[],Instagram:[]},posts=[],warnings=[],channelLabels={};for(const org of orgs){try{const result=await bufferCall('query Channels($organization:OrganizationId!){channels(input:{organizationId:$organization}){id name displayName service}}',{organization:org.id});for(const platform of ['Facebook','Instagram']){if(platformFilter!=='all'&&platformFilter!==platform.toLowerCase())continue;const ids=(result.channels||[]).filter(x=>String(x.service).toLowerCase()===platform.toLowerCase()).map(x=>{channelLabels[x.id]=platform;return x.id});if(!ids.length)continue;try{groups[platform].push(await bufferAggregate(org.id,ids,start,end));priorGroups[platform].push(await bufferAggregate(org.id,ids,previousStart,start))}catch(e){warnings.push(`${platform} metrics: ${e.message}`)}try{const query='query Insights($organization:OrganizationId!,$channels:[ChannelId!]!,$start:DateTime!,$after:String){posts(first:100,after:$after,input:{organizationId:$organization,sort:[{field:dueAt,direction:desc}],filter:{status:[sent],channelIds:$channels,startDate:$start}}){edges{node{id text dueAt channelId externalLink metrics{type name value unit} metricsUpdatedAt}}}}';const data=await bufferCall(query,{organization:org.id,channels:ids,start:start.toISOString(),after:null});posts.push(...(data.posts?.edges||[]).map(x=>({...x.node,platform:channelLabels[x.node.channelId]||platform})))}catch(e){warnings.push(`${platform} top posts: ${e.message}`)}}}catch(e){warnings.push(`${org.name||org.id}: ${e.message}`)}}const currentGroups=Object.values(groups).flat(),allPrior=Object.values(priorGroups).flat();if(!currentGroups.length&&!allPrior.length)throw Error(warnings[0]||'No Facebook or Instagram metrics were returned');const current=summarizeAggregate(currentGroups,start,end),previous=summarizeAggregate(allPrior,previousStart,start);current.posts=summarize(posts,start,end).posts.slice(0,50);const platforms={};for(const name of ['Facebook','Instagram'])if(groups[name].length)platforms[name]=summarizeAggregate(groups[name],start,end);return {days,platform:platformFilter,start:start.toISOString(),end:end.toISOString(),current,previous,platforms,channels:Object.keys(channelLabels).length,warnings,experimental:true}}
async function marketingTasks(){const c=db.integrations.vikunja;if(!c.url||!c.token)return {configured:false,tasks:[]};const headers={Authorization:`Bearer ${c.token}`,Accept:'application/json'},base=apiBase(c.url),projects=await fetchJson(`${base}/projects?per_page=100`,{headers},'Vikunja'),wanted=(Array.isArray(projects)?projects:[]).filter(project=>['night of the living loud','rage for democracy'].includes(String(project.title||'').toLowerCase())),tasks=[];for(const project of wanted){for(let page=1;page<=10;page++){const batch=await fetchJson(`${base}/projects/${project.id}/tasks?page=${page}&per_page=50`,{headers},'Vikunja marketing tasks');if(!Array.isArray(batch)||!batch.length)break;for(const task of batch){const labels=(task.labels||[]).map(label=>String(label.title||'').toLowerCase());if(labels.some(label=>label.includes('marketing')||label.includes('advertising')))tasks.push({id:task.id,title:task.title||'Untitled task',project:project.title,done:Boolean(task.done),dueDate:task.due_date||'',assignees:(task.assignees||[]).map(person=>person.username||person.name||`User ${person.id}`),labels:(task.labels||[]).map(label=>label.title),url:`${String(c.url).replace(/\/$/,'')}/tasks/${task.id}`})}if(batch.length<50)break}}return {configured:true,tasks:tasks.sort((a,b)=>Number(a.done)-Number(b.done)||String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')))}}
async function draftDonationLetter(payload){const base=String(process.env.RFD_WRITER_URL||'').replace(/\/$/,'');if(!base)throw Error('Set RFD_WRITER_URL so the Hub can write the letter with the Rage assistant');const prompt=`Write a polished donation or sponsorship request letter for Rage for Democracy.\nRecipient/business: ${clean(payload.businessName)}\nPurpose: ${clean(payload.purpose)}\nEvent: ${clean(payload.eventName||payload.event_name)}\nEvent date: ${clean(payload.eventDate||payload.event_date)}\nSigner: ${clean(payload.signerName)}\nNotes: ${clean(payload.body)}\n\nUse a professional, persuasive, community-focused voice. Include a greeting, clear request, why the support matters, and a gracious closing signed exactly as ${clean(payload.signerName)}. Do not invent contact information, titles, tax claims, statistics, or benefits not supplied. Return only the finished letter body in plain text. Do not call tools.`;let response;try{response=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'Content-Type':'application/json',...(process.env.RFD_WRITER_TOKEN?{Authorization:`Bearer ${process.env.RFD_WRITER_TOKEN}`}:{})},body:JSON.stringify({model:process.env.RFD_WRITER_MODEL||'rage-assistant',stream:false,messages:[{role:'user',content:prompt}],temperature:.35}),signal:AbortSignal.timeout(180000)})}catch(error){throw Error(`Could not reach Rage writer at ${base}${error.cause?.code?` (${error.cause.code})`:''}`)}const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error?.message||data.error||`Rage writer returned ${response.status}`);const text=clean(data.choices?.[0]?.message?.content);if(!text)throw Error('Rage writer returned no letter text');return text}
async function runPdfJob(job,payload){const base=String(process.env.PDF_GENERATOR_URL||'').replace(/\/$/,'');try{job.status='writing';job.progress=15;const letter=await draftDonationLetter(payload);job.status='generating';job.progress=55;const response=await fetch(`${base}/generate-donation-letter`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,body:letter,recipient_name:payload.businessName,sender_name:payload.signerName,name:payload.signerName,post_to_outline:false,attach_pdf:false}),signal:AbortSignal.timeout(300000)});job.progress=80;if(!response.ok)throw Error(`PDF generator returned ${response.status}: ${(await response.text()).slice(0,300)}`);const type=response.headers.get('content-type')||'';let bytes;if(type.includes('application/pdf'))bytes=Buffer.from(await response.arrayBuffer());else{const result=await response.json(),encoded=result.pdf_base64||result.pdfBase64,source=result.pdf_url||result.download_url||result.url||result.pdfUrl;if(encoded)bytes=Buffer.from(String(encoded).replace(/^data:[^;]+;base64,/,''),'base64');else if(source){const download=new URL(source,`${base}/`),pdfResponse=await fetch(download,{signal:AbortSignal.timeout(300000)});if(!pdfResponse.ok)throw Error(`Generated PDF download returned ${pdfResponse.status}`);bytes=Buffer.from(await pdfResponse.arrayBuffer())}else throw Error('PDF generator did not return a downloadable PDF')}if(!bytes?.length)throw Error('PDF generator returned an empty file');const dir=join(DATA,'generated-pdfs'),stored=`${job.id}.pdf`;await mkdir(dir,{recursive:true});await writeFile(join(dir,stored),bytes);Object.assign(job,{stored,name:`${clean(payload.businessName).replace(/[^a-z0-9 _-]/gi,'')||'donation-letter'}.pdf`,businessName:clean(payload.businessName),purpose:clean(payload.purpose),signerName:clean(payload.signerName),status:'ready',progress:100,completedAt:new Date().toISOString(),size:bytes.length});db.generatedPdfs.unshift(job);db.generatedPdfs=db.generatedPdfs.slice(0,50);await save()}catch(error){job.status='failed';job.error=error.cause?.code?`Could not reach PDF generator at ${base} (${error.cause.code})`:error.message==='fetch failed'?`Could not reach PDF generator at ${base}`:error.message;job.progress=100}}
async function api(req,res,url){
 if(url==='/api/session'&&req.method==='GET')return json(res,200,{version:APP_VERSION,authenticated:Boolean(session(req)||process.env.AUTH_BYPASS==='true'),configured:configured()||Boolean(db.integrations.keycloak.enabled),keycloak:Boolean(db.integrations.keycloak.enabled),boardPasswordConfigured:configured(),boardPasswordLogin:process.env.ALLOW_BOARD_PASSWORD_LOGIN!=='false',name:session(req)?.name||'Board member'});
 if(url==='/api/login'&&req.method==='POST'){const b=await body(req),enteredPassword=String(b.password||''),bootstrapAllowed=process.env.ALLOW_BOARD_PASSWORD_LOGIN!=='false';let identity;if(db.integrations.keycloak.enabled&&!(bootstrapAllowed&&passwordOk(enteredPassword))){try{identity=await keycloakLogin(clean(b.name),enteredPassword)}catch(e){return json(res,401,{error:e.message})}}else{if(!configured())return json(res,503,{error:'Set BOARD_PASSWORD before inviting board members.'});if(!passwordOk(enteredPassword))return json(res,401,{error:'That password was not accepted.'});identity={name:clean(b.name)||'Board administrator',at:Date.now(),bootstrap:true}}const sid=randomBytes(32).toString('hex');sessions.set(sid,identity);res.setHeader('set-cookie',`rfd_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${secureRequest(req)?'; Secure':''}`);return json(res,200,{ok:true})}
 if(url==='/api/logout'&&req.method==='POST'){sessions.delete(cookies(req).rfd_session);res.setHeader('set-cookie','rfd_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 const user=requireAuth(req,res);if(!user)return;
 if(url==='/api/marketing-workspace'&&req.method==='GET'){try{return json(res,200,await marketingTasks())}catch(e){return json(res,200,{configured:Boolean(db.integrations.vikunja.url&&db.integrations.vikunja.token),tasks:[],error:e.message})}}
 if(url==='/api/marketing-assets'&&req.method==='GET')return json(res,200,{items:db.marketingAssets});
 if(url==='/api/marketing-assets'&&req.method==='POST'){const b=await body(req),mimeType=clean(b.mime).toLowerCase(),allowed={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','application/pdf':'.pdf'};if(!allowed[mimeType])return json(res,400,{error:'Assets must be JPG, PNG, WebP, or PDF'});const encoded=String(b.data||'').replace(/^data:[^;]+;base64,/,'');let bytes;try{bytes=Buffer.from(encoded,'base64')}catch{return json(res,400,{error:'Asset data is invalid'})}if(!bytes.length||bytes.length>20_000_000)return json(res,400,{error:'Asset must be between 1 byte and 20 MB'});const assetId=id(),stored=`${assetId}${allowed[mimeType]}`,dir=join(DATA,'marketing-assets');await mkdir(dir,{recursive:true});await writeFile(join(dir,stored),bytes);const item={id:assetId,stored,name:clean(b.name).slice(0,150)||`marketing-asset${allowed[mimeType]}`,mime:mimeType,size:bytes.length,uploadedAt:new Date().toISOString(),uploadedBy:user.name};db.marketingAssets.unshift(item);audit(user,'marketing.asset',item.name);await save();return json(res,201,item)}
 const assetMatch=url.match(/^\/api\/marketing-assets\/([^/]+)\/download$/);if(assetMatch&&req.method==='GET'){const item=db.marketingAssets.find(x=>x.id===assetMatch[1]);if(!item)return json(res,404,{error:'Asset not found'});try{const bytes=await readFile(join(DATA,'marketing-assets',item.stored));res.writeHead(200,{'content-type':item.mime,'content-length':bytes.length,'content-disposition':`attachment; filename="${item.name.replace(/["\\]/g,'_')}"`,'cache-control':'private, no-store','x-content-type-options':'nosniff'});return res.end(bytes)}catch{return json(res,404,{error:'Asset file is missing'})}}
 if(url==='/api/pdf-jobs'&&req.method==='GET')return json(res,200,{items:db.generatedPdfs.map(({result,...item})=>item)});
 if(url==='/api/pdf-jobs'&&req.method==='POST'){if(!process.env.PDF_GENERATOR_URL)return json(res,503,{error:'Set PDF_GENERATOR_URL on the server first'});const b=await body(req);if(!clean(b.businessName)||!clean(b.purpose))return json(res,400,{error:'Business name and purpose are required'});b.signerName=b.useSignerOverride&&clean(b.signerOverride)?clean(b.signerOverride):clean(user.name)||'Board member';const job={id:id(),status:'queued',progress:5,createdAt:new Date().toISOString(),createdBy:user.name,signerName:b.signerName};pdfJobs.set(job.id,job);audit(user,'marketing.pdf',clean(b.businessName));await save();runPdfJob(job,b);return json(res,202,job)}
 const pdfMatch=url.match(/^\/api\/pdf-jobs\/([^/]+)(\/download)?$/);if(pdfMatch&&req.method==='GET'){const job=pdfJobs.get(pdfMatch[1]);if(!job)return json(res,404,{error:'PDF job not found or expired'});if(!pdfMatch[2])return json(res,200,job);if(job.status!=='ready')return json(res,409,{error:'PDF is not ready'});try{const bytes=await readFile(join(DATA,'generated-pdfs',job.stored));res.writeHead(200,{'content-type':'application/pdf','content-length':bytes.length,'content-disposition':`attachment; filename="${String(job.name||'document.pdf').replace(/["\\]/g,'_')}"`,'cache-control':'private, no-store'});return res.end(bytes)}catch{return json(res,404,{error:'Generated PDF is missing'})}}
 const receiptMatch=url.match(/^\/api\/transactions\/([^/]+)\/receipt$/);if(receiptMatch){const transaction=db.transactions.find(x=>x.id===receiptMatch[1]);if(!transaction)return json(res,404,{error:'Transaction not found'});if(req.method==='POST'){const b=await body(req),mime=clean(b.mime).toLowerCase(),allowed={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','application/pdf':'.pdf'};if(!allowed[mime])return json(res,400,{error:'Receipts must be JPG, PNG, WebP, or PDF'});const encoded=String(b.data||'').replace(/^data:[^;]+;base64,/,'');let bytes;try{bytes=Buffer.from(encoded,'base64')}catch{return json(res,400,{error:'Receipt data is invalid'})}if(!bytes.length||bytes.length>8_000_000)return json(res,400,{error:'Receipt must be between 1 byte and 8 MB'});const receiptDir=join(DATA,'receipts'),stored=`${transaction.id}${allowed[mime]}`;await mkdir(receiptDir,{recursive:true});await writeFile(join(receiptDir,stored),bytes);transaction.receipt={stored,name:clean(b.name).slice(0,150)||`receipt${allowed[mime]}`,mime,size:bytes.length,uploadedAt:new Date().toISOString()};audit(user,'transactions.receipt',transaction.description);await save();return json(res,200,{receipt:transaction.receipt})}if(req.method==='GET'){if(!transaction.receipt?.stored)return json(res,404,{error:'No receipt attached'});try{const bytes=await readFile(join(DATA,'receipts',transaction.receipt.stored));res.writeHead(200,{'content-type':transaction.receipt.mime,'content-length':bytes.length,'content-disposition':`inline; filename="${transaction.receipt.name.replace(/["\\]/g,'_')}"`,'cache-control':'private, no-store','x-content-type-options':'nosniff'});return res.end(bytes)}catch{return json(res,404,{error:'Receipt file is missing'})}}return json(res,405,{error:'Method not allowed'})}
 if(url==='/api/dashboard'&&req.method==='GET'){const income=db.transactions.filter(x=>x.type==='Income').reduce((s,x)=>s+Number(x.amount||0),0),expenses=db.transactions.filter(x=>x.type==='Expense').reduce((s,x)=>s+Number(x.amount||0),0);return json(res,200,{finance:{income,expenses,balance:income-expenses,count:db.transactions.length},marketing:{open:db.marketing.filter(x=>x.status!=='Done').length,total:db.marketing.length},newsletters:{active:db.newsletters.filter(x=>x.status!=='Published').length},activity:db.activity.slice(0,8)})}
 if(url==='/api/events'&&req.method==='GET')return json(res,200,{events:db.events.map(event=>({id:event.id,title:event.title}))});
 if(url==='/api/integrations'&&req.method==='GET'){const c=structuredClone(db.integrations);for(const x of Object.values(c)){if(x.token)x.token='configured';if(x.clientSecret)x.clientSecret='configured'}return json(res,200,{integrations:c})}
 if(url==='/api/integrations'&&req.method==='PUT'){const b=await body(req),old=db.integrations,next=b.integrations||{},kc=next.keycloak||{};db.integrations={keycloak:{url:clean(kc.url),realm:clean(kc.realm),clientId:clean(kc.clientId)||'rfd-board-hub',clientSecret:clean(kc.clientSecret)==='configured'||!clean(kc.clientSecret)?old.keycloak.clientSecret:clean(kc.clientSecret),enabled:kc.enabled===true},vikunja:{url:clean(next.vikunja?.url),project:clean(next.vikunja?.project)||'Night of the Living Loud',token:clean(next.vikunja?.token)==='configured'||!clean(next.vikunja?.token)?old.vikunja.token:clean(next.vikunja.token)},eventbrite:{eventId:clean(next.eventbrite?.eventId),token:clean(next.eventbrite?.token)==='configured'||!clean(next.eventbrite?.token)?old.eventbrite.token:clean(next.eventbrite.token)},buffer:{facebookChannel:clean(next.buffer?.facebookChannel),instagramChannel:clean(next.buffer?.instagramChannel),token:clean(next.buffer?.token)==='configured'||!clean(next.buffer?.token)?old.buffer.token:clean(next.buffer.token)}};audit(user,'integrations.update','Board integrations');await save();return json(res,200,{ok:true})}
 if(url==='/api/living-loud'&&req.method==='GET'){try{return json(res,200,{configured:true,data:await livingLoud()})}catch(e){return json(res,200,{configured:Boolean(db.integrations.vikunja.url),error:e.message})}}
 if(url==='/api/insights'&&req.method==='GET'){try{const query=new URL(req.url,'http://localhost'),days=Math.max(1,Math.min(365,Number(query.searchParams.get('days')||30))),platform=['facebook','instagram'].includes(query.searchParams.get('platform'))?query.searchParams.get('platform'):'all',data=await bufferInsightsRich(days,platform);return json(res,200,{configured:true,data})}catch(e){return json(res,200,{configured:Boolean(db.integrations.buffer.token),error:e.message})}}
 if(url==='/api/insights-targets'&&req.method==='GET')return json(res,200,{targets:db.insightsTargets||{}});
 if(url==='/api/insights-targets'&&req.method==='PUT'){const b=await body(req),targets={};for(const key of ['engagements','reach','follows','clicks','posts']){const value=Number(b[key]||0);if(!Number.isFinite(value)||value<0)return json(res,400,{error:`${key} target must be a positive number`});targets[key]=value}db.insightsTargets=targets;audit(user,'insights.targets','30-day goals');await save();return json(res,200,{targets})}
 const match=url.match(/^\/api\/(transactions|marketing|newsletters)(?:\/([^/]+))?$/);if(match){const [,collection,itemId]=match;
   if(req.method==='GET'){const items=collection==='transactions'?[...db.transactions].sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||String(b.id||'').localeCompare(String(a.id||''))):db[collection];return json(res,200,{items})}
   if(req.method==='POST'){const b=await body(req),item={...b,id:id()};db[collection].unshift(item);audit(user,`${collection}.create`,item.title||item.description);await save();return json(res,201,item)}
   if(req.method==='PUT'&&itemId){const ix=db[collection].findIndex(x=>x.id===itemId);if(ix<0)return json(res,404,{error:'Not found'});const b=await body(req);db[collection][ix]={...db[collection][ix],...b,id:itemId};audit(user,`${collection}.update`,db[collection][ix].title||db[collection][ix].description);await save();return json(res,200,db[collection][ix])}
 }
 return json(res,404,{error:'Not found'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost').pathname;if(url==='/health')return json(res,200,{ok:true,service:'rfd-board-hub',version:APP_VERSION});if(url.startsWith('/api/'))return await api(req,res,url);const path=join(PUBLIC,url==='/'?'index.html':url);if(!path.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});const data=await readFile(path);res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; frame-ancestors 'none'"});res.end(data)}catch(e){if(e.code==='ENOENT')json(res,404,{error:'Not found'});else{console.error(e);json(res,500,{error:'Unexpected server error'})}}});
if(process.env.NODE_ENV!=='test')server.listen(PORT,()=>console.log(`RFD Board Hub listening on http://localhost:${PORT}`));
export {server,passwordOk,summarizeAggregate,secureRequest};
