import http from 'node:http';
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {join, extname} from 'node:path';
import {randomBytes, timingSafeEqual, scryptSync} from 'node:crypto';
import {fileURLToPath} from 'node:url';

const PORT=Number(process.env.PORT||4380), ROOT=fileURLToPath(new URL('.',import.meta.url)), PUBLIC=join(ROOT,'public'), DATA=process.env.DATA_DIR||join(ROOT,'data'), DB=join(DATA,'hub.json');
const sessions=new Map(), maxBody=1_000_000;
const seed={transactions:[],marketing:[{id:'welcome',title:'Build the fall campaign calendar',owner:'Communications',status:'In progress',due:'',channel:'All channels'}],newsletters:[{id:'first-issue',title:'Next RFD newsletter',status:'Outline',writer:'',due:'',sections:[{id:'opening',title:'Opening note',notes:'Why this moment matters',status:'Drafting'},{id:'action',title:'Action items',notes:'Events, volunteer asks, and links',status:'Needs input'}]}],integrations:{vikunja:{url:'',token:'',project:'Night of the Living Loud'},eventbrite:{eventId:'',token:''},buffer:{token:'',facebookChannel:'',instagramChannel:''}},eventMetrics:{sponsorsCommitted:0,revenueCommitted:0},activity:[]};
let db=await load();
async function load(){await mkdir(DATA,{recursive:true});if(!existsSync(DB)){await writeFile(DB,JSON.stringify(seed,null,2));return structuredClone(seed)}try{return {...structuredClone(seed),...JSON.parse(await readFile(DB,'utf8'))}}catch{return structuredClone(seed)}}
async function save(){await writeFile(DB,JSON.stringify(db,null,2))}
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=').map(decodeURIComponent)));
const session=req=>sessions.get(cookies(req).rfd_session);
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>maxBody)throw Error('Request too large')}return raw?JSON.parse(raw):{}}
function hash(value,salt){return scryptSync(value,salt,32)}
function configured(){return Boolean(process.env.BOARD_PASSWORD_HASH&&process.env.BOARD_PASSWORD_SALT)||Boolean(process.env.BOARD_PASSWORD)}
function passwordOk(value){if(process.env.BOARD_PASSWORD_HASH&&process.env.BOARD_PASSWORD_SALT){const got=hash(value,process.env.BOARD_PASSWORD_SALT),expected=Buffer.from(process.env.BOARD_PASSWORD_HASH,'hex');return got.length===expected.length&&timingSafeEqual(got,expected)}return Boolean(process.env.BOARD_PASSWORD)&&value===process.env.BOARD_PASSWORD}
function requireAuth(req,res){if(process.env.AUTH_BYPASS==='true')return {name:'Local preview'};const s=session(req);if(!s){json(res,401,{error:'Sign in required'});return null}return s}
const clean=v=>String(v??'').trim().slice(0,5000), id=()=>randomBytes(8).toString('hex');
function audit(user,action,label){db.activity.unshift({id:id(),at:new Date().toISOString(),user:user.name,action,label:clean(label).slice(0,100)});db.activity=db.activity.slice(0,100)}
const apiBase=url=>`${String(url||'').replace(/\/$/,'').replace(/\/api\/v1$/,'')}/api/v1`;
async function fetchJson(url,options={},label='Service'){const r=await fetch(url,{...options,signal:AbortSignal.timeout(15000)}),text=await r.text();let data;try{data=JSON.parse(text)}catch{throw Error(`${label} returned invalid data`)}if(!r.ok)throw Error(data.message||data.error_description||data.error||`${label} returned ${r.status}`);return data}
async function eventbriteSnapshot(){const c=db.integrations.eventbrite;if(!c.eventId||!c.token)throw Error('Configure Eventbrite in Settings');const headers={Authorization:`Bearer ${c.token}`,Accept:'application/json'},base='https://www.eventbriteapi.com/v3',event=await fetchJson(`${base}/events/${encodeURIComponent(c.eventId)}/`,{headers},'Eventbrite'),attendees=[],orders=[];for(let page=1;page<=50;page++){const d=await fetchJson(`${base}/events/${c.eventId}/attendees/?page=${page}`,{headers},'Eventbrite attendees');attendees.push(...(d.attendees||[]));if(!d.pagination?.has_more_items)break}for(let page=1;page<=50;page++){const d=await fetchJson(`${base}/events/${c.eventId}/orders/?page=${page}`,{headers},'Eventbrite orders');orders.push(...(d.orders||[]));if(!d.pagination?.has_more_items)break}const active=attendees.filter(x=>!x.cancelled&&!x.refunded),byTicket={};for(const x of active){const name=x.ticket_class_name||'Other';byTicket[name]=(byTicket[name]||0)+Math.max(1,Number(x.quantity)||1)}return {event:event.name?.text||'Night of the Living Loud',ticketsSold:active.length,checkedIn:active.filter(x=>x.checked_in).length,orders:orders.filter(x=>!x.status||x.status==='placed').length,grossRevenue:active.reduce((s,x)=>s+Number(x.costs?.gross?.value||0),0)/100,capacity:Number(event.capacity||0),byTicket}}
async function livingLoud(){const c=db.integrations.vikunja;if(!c.url||!c.token)throw Error('Configure Vikunja in Settings');const headers={Authorization:`Bearer ${c.token}`,Accept:'application/json'},base=apiBase(c.url),projects=await fetchJson(`${base}/projects?per_page=100`,{headers},'Vikunja'),project=(Array.isArray(projects)?projects:[]).find(x=>String(x.title).toLowerCase()===String(c.project).toLowerCase());if(!project)throw Error(`Vikunja project “${c.project}” was not found`);const tasks=[];for(let page=1;page<=20;page++){const batch=await fetchJson(`${base}/projects/${project.id}/tasks?page=${page}&per_page=50`,{headers},'Vikunja tasks');if(!Array.isArray(batch)||!batch.length)break;tasks.push(...batch);if(batch.length<50)break}const now=Date.now(),week=now+7*864e5,item=x=>{const due=x.due_date||'',t=new Date(due).getTime();return {id:x.id,title:x.title,done:Boolean(x.done),dueDate:due,overdue:Boolean(!x.done&&t&&t<now),priority:Number(x.priority||0),assignees:(x.assignees||[]).map(p=>p.username||p.name||`User ${p.id}`)}};const items=tasks.map(item),open=items.filter(x=>!x.done),people={};for(const task of open)for(const person of task.assignees)people[person]=(people[person]||0)+1;let ticketing=null;try{ticketing=await eventbriteSnapshot()}catch(e){ticketing={error:e.message}}return {project:{title:project.title,url:`${String(c.url).replace(/\/$/,'')}/projects/${project.id}`},metrics:db.eventMetrics,ticketing,summary:{total:items.length,done:items.length-open.length,open:open.length,overdue:open.filter(x=>x.overdue).length,completion:items.length?Math.round((items.length-open.length)/items.length*100):0},people,upcoming:open.filter(x=>{const t=new Date(x.dueDate).getTime();return t>=now&&t<=week}).slice(0,12),urgent:open.filter(x=>x.priority>=4||x.overdue).slice(0,12)} }
async function bufferCall(query,variables={}){const token=db.integrations.buffer.token;if(!token)throw Error('Configure Buffer in Settings');return (await fetchJson('https://api.buffer.com',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({query,variables})},'Buffer')).data||{}}
const metricKey=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function summarize(posts,start,end){const selected=[],totals={};for(const post of posts){const published=new Date(post.dueAt);if(!(published>=start&&published<end))continue;const values={};for(const m of post.metrics||[]){const k=metricKey(m.type||m.name),v=Number(m.value||0);values[k]=v;totals[k]=(totals[k]||0)+v}const engagements=(values.reactions??values.likes??0)+['comments','shares','saves','clicks','linkclicks'].reduce((s,k)=>s+(values[k]||0),0),reach=values.reach||values.impressions||0;selected.push({...post,metricValues:values,derivedEngagements:engagements,derivedEngagementRate:reach?engagements/reach*100:null})}selected.sort((a,b)=>(b.derivedEngagementRate??-1)-(a.derivedEngagementRate??-1));const engagements=selected.reduce((s,x)=>s+x.derivedEngagements,0),reach=totals.reach||totals.impressions||0,count=selected.length;return {postCount:count,totals,derived:{engagements,engagementRate:reach?engagements/reach*100:null,averageEngagements:count?engagements/count:0,postsPerWeek:count/Math.max((end-start)/6048e5,1/7)},posts:selected}}
async function bufferInsights(){const account=await bufferCall('query { account { organizations { id name } } }'),orgs=account.account?.organizations||[];if(!orgs.length)throw Error('Buffer returned no organizations');const chosen=[db.integrations.buffer.facebookChannel,db.integrations.buffer.instagramChannel].filter(Boolean),end=new Date(),start=new Date(end-30*864e5),previous=new Date(start-30*864e5),posts=[];for(const org of orgs){let ids=chosen;if(!ids.length){const result=await bufferCall('query Channels($organization:OrganizationId!){channels(input:{organizationId:$organization}){id service}}',{organization:org.id});ids=(result.channels||[]).filter(x=>['facebook','instagram'].includes(String(x.service).toLowerCase())).map(x=>x.id)}if(!ids.length)continue;const query='query Insights($organization:OrganizationId!,$channels:[ChannelId!]!,$start:DateTime!,$after:String){posts(first:100,after:$after,input:{organizationId:$organization,sort:[{field:dueAt,direction:desc}],filter:{status:[sent],channelIds:$channels,startDate:$start}}){edges{node{id text dueAt channelId externalLink metrics{type name value unit} metricsUpdatedAt}}}}';const result=await bufferCall(query,{organization:org.id,channels:ids,start:previous.toISOString(),after:null});posts.push(...(result.posts?.edges||[]).map(x=>x.node))}return {days:30,current:summarize(posts,start,end),previous:summarize(posts,previous,start),channels:chosen.length||'auto'} }
async function api(req,res,url){
 if(url==='/api/session'&&req.method==='GET')return json(res,200,{authenticated:Boolean(session(req)||process.env.AUTH_BYPASS==='true'),configured:configured(),name:session(req)?.name||'Board member'});
 if(url==='/api/login'&&req.method==='POST'){const b=await body(req);if(!configured())return json(res,503,{error:'Set BOARD_PASSWORD before inviting board members.'});if(!passwordOk(String(b.password||'')))return json(res,401,{error:'That password was not accepted.'});const sid=randomBytes(32).toString('hex');sessions.set(sid,{name:clean(b.name)||'Board member',at:Date.now()});res.setHeader('set-cookie',`rfd_session=${sid}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${process.env.NODE_ENV==='production'?'; Secure':''}`);return json(res,200,{ok:true})}
 if(url==='/api/logout'&&req.method==='POST'){sessions.delete(cookies(req).rfd_session);res.setHeader('set-cookie','rfd_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 const user=requireAuth(req,res);if(!user)return;
 if(url==='/api/dashboard'&&req.method==='GET'){const income=db.transactions.filter(x=>x.type==='Income').reduce((s,x)=>s+Number(x.amount||0),0),expenses=db.transactions.filter(x=>x.type==='Expense').reduce((s,x)=>s+Number(x.amount||0),0);return json(res,200,{finance:{income,expenses,balance:income-expenses,count:db.transactions.length},marketing:{open:db.marketing.filter(x=>x.status!=='Done').length,total:db.marketing.length},newsletters:{active:db.newsletters.filter(x=>x.status!=='Published').length},activity:db.activity.slice(0,8)})}
 if(url==='/api/integrations'&&req.method==='GET'){const c=structuredClone(db.integrations);for(const x of Object.values(c))if(x.token)x.token='configured';return json(res,200,{integrations:c})}
 if(url==='/api/integrations'&&req.method==='PUT'){const b=await body(req),old=db.integrations,next=b.integrations||{};db.integrations={vikunja:{url:clean(next.vikunja?.url),project:clean(next.vikunja?.project)||'Night of the Living Loud',token:clean(next.vikunja?.token)==='configured'||!clean(next.vikunja?.token)?old.vikunja.token:clean(next.vikunja.token)},eventbrite:{eventId:clean(next.eventbrite?.eventId),token:clean(next.eventbrite?.token)==='configured'||!clean(next.eventbrite?.token)?old.eventbrite.token:clean(next.eventbrite.token)},buffer:{facebookChannel:clean(next.buffer?.facebookChannel),instagramChannel:clean(next.buffer?.instagramChannel),token:clean(next.buffer?.token)==='configured'||!clean(next.buffer?.token)?old.buffer.token:clean(next.buffer.token)}};audit(user,'integrations.update','Board integrations');await save();return json(res,200,{ok:true})}
 if(url==='/api/living-loud'&&req.method==='GET'){try{return json(res,200,{configured:true,data:await livingLoud()})}catch(e){return json(res,200,{configured:Boolean(db.integrations.vikunja.url),error:e.message})}}
 if(url==='/api/insights'&&req.method==='GET'){try{const data=await bufferInsights(),c=data.current;c.post_count=c.postCount;c.total_engagements=c.derived.engagements;c.engagement_rate=Number((c.derived.engagementRate||0).toFixed(2));c.posts_per_week=Number(c.derived.postsPerWeek.toFixed(1));for(const p of c.posts)p.engagements=p.derivedEngagements;return json(res,200,{configured:true,data})}catch(e){return json(res,200,{configured:Boolean(db.integrations.buffer.token),error:e.message})}}
 const match=url.match(/^\/api\/(transactions|marketing|newsletters)(?:\/([^/]+))?$/);if(match){const [,collection,itemId]=match;
   if(req.method==='GET')return json(res,200,{items:db[collection]});
   if(req.method==='POST'){const b=await body(req),item={...b,id:id()};db[collection].unshift(item);audit(user,`${collection}.create`,item.title||item.description);await save();return json(res,201,item)}
   if(req.method==='PUT'&&itemId){const ix=db[collection].findIndex(x=>x.id===itemId);if(ix<0)return json(res,404,{error:'Not found'});const b=await body(req);db[collection][ix]={...db[collection][ix],...b,id:itemId};audit(user,`${collection}.update`,db[collection][ix].title||db[collection][ix].description);await save();return json(res,200,db[collection][ix])}
 }
 return json(res,404,{error:'Not found'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost').pathname;if(url.startsWith('/api/'))return await api(req,res,url);const path=join(PUBLIC,url==='/'?'index.html':url);if(!path.startsWith(PUBLIC))return json(res,403,{error:'Forbidden'});const data=await readFile(path);res.writeHead(200,{'content-type':mime[extname(path)]||'application/octet-stream','x-content-type-options':'nosniff','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; frame-ancestors 'none'"});res.end(data)}catch(e){if(e.code==='ENOENT')json(res,404,{error:'Not found'});else{console.error(e);json(res,500,{error:'Unexpected server error'})}}});
if(process.env.NODE_ENV!=='test')server.listen(PORT,()=>console.log(`RFD Board Hub listening on http://localhost:${PORT}`));
export {server,passwordOk};
